blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://docs.storacha.network
    about: Check the official Storacha documentation
  - name: 💬 Discussions
    url: #
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: #
    about: Report security vulnerabilities privately
